export const GET_ALL_GAPF = "GET_ALL_GAPF";

export const UPDATE_LINK = "UPDATE_LINK";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const RESOLVE_NOTE = 'RESOLVE_NOTE';
export const DISABLE_NOTES = 'DISABLE_NOTES';
export const ENABLE_NOTES = 'ENABLE_NOTES';
export const CONFIRM_ADD_NOTE = 'CONFIRM_ADD_NOTE';
export const CONFIRM_DELETE_NOTE = 'CONFIRM_DELETE_NOTE';
export const CONFIRM_RESOLVE_NOTE = 'CONFIRM_RESOLVE_NOTE';
