export const INCREMENT_REQUESTED = "INCREMENT_REQUESTED";
export const INCREMENT = "INCREMENT";
export const DECREMENT_REQUESTED = "DECREMENT_REQUESTED";
export const DECREMENT = "DECREMENT";

export const GET_ALL_GAPF = "GET_ALL_GAPF";
