export const GET_ALL_GAPF = "GET_ALL_GAPF";

export const UPDATE_LINK = "UPDATE_LINK";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";

export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const ADD_TICKETS = 'ADD_TICKETS';
export const GET_TICKET = 'GET_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';


export const UPDATE_NOTE = 'UPDATE_NOTE';
export const RESOLVE_NOTE = 'RESOLVE_NOTE';
export const DISABLE_NOTES = 'DISABLE_NOTES';
export const ENABLE_NOTES = 'ENABLE_NOTES';
export const CONFIRM_ADD_NOTE = 'CONFIRM_ADD_NOTE';
export const CONFIRM_DELETE_NOTE = 'CONFIRM_DELETE_NOTE';
export const CONFIRM_RESOLVE_NOTE = 'CONFIRM_RESOLVE_NOTE';
export const ENABLE_TICKETS = 'ENABLE_TICKETS';
export const DISABLE_TICKETS = 'DISABLE_TICKETS';
export const LOAD_TICKETS = 'LOAD_TICKETS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_FACULTY_GAPF = 'GET_FACULTY_GAPF';