apiVersion: apps/v1
kind: Deployment
metadata:
  name: javelin 
  labels:
     name: javelin 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: javelin 
  template:
    metadata:
      labels:
        name: javelin 
    spec:
      containers:
      - name: javelin 
        image: localhost:5000/javelin
        ports:
        - containerPort: 50053 
        imagePullPolicy: IfNotPresent
