apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouroboros
  labels:
     name: ouroboros
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ouroboros
  template:
    metadata:
      labels:
        name: ouroboros 
    spec:
      containers:
      - name: ouroboros 
        image: localhost:5000/ouroboros
        ports:
        - containerPort: 31000 
        imagePullPolicy: IfNotPresent

