apiVersion: apps/v1
kind: Deployment
metadata:
  name: populous 
  labels:
     name: populous 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: populous 
  template:
    metadata:
      labels:
        name: populous 
    spec:
      containers:
      - name: populous 
        image: localhost:5000/populous
        ports:
        - containerPort: 50052 
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_USER
          value: "admin"
        - name: MONGO_PASS
          value: "Y70TcYY3BVVKK7zp"
