apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident 
  labels:
     name: trident 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: trident 
  template:
    metadata:
      labels:
        name: trident 
    spec:
      containers:
      - name: trident 
        image: abrarisme/trident
        ports:
        - containerPort: 8080
