apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident 
  labels:
     name: trident 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: trident 
  template:
    metadata:
      labels:
        name: trident 
    spec:
      containers:
      - name: trident 
        image: localhost:5000/trident
        ports:
        - containerPort: 50051 
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_USER
          value: "admin"
        - name: MONGO_PASS
          value: "Y70TcYY3BVVKK7zp"
