apiVersion: v1
kind: Service
metadata:
  name: ouroboros
  labels:
    name: ouroboros
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 8080 
    nodePort: 31000
  selector:
    name: ouroboros
  type: NodePort 
