apiVersion: v1
kind: Service
metadata:
  name: populous 
  labels:
    name: populous 
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 8080 
  selector:
    name: populous 
  type: ClusterIP
