apiVersion: v1
kind: Service
metadata:
  name: scythe 
  labels:
    name: scythe 
spec:
  ports:
  - port: 3000 
    protocol: TCP
    targetPort: 3000 
    nodePort: 31001
  selector:
    name: scythe 
  type: NodePort 
