apiVersion: v1
kind: Service
metadata:
  name: trident 
  labels:
    name: trident 
spec:
  ports:
  - port: 50051 
    protocol: TCP
    targetPort: 50051 
  selector:
    name: trident 
  type: ClusterIP
